#!/bin/bash
# OpenClaw Notebook — Apple Reminders Setup
# Creates the required Reminders lists.

echo ""
echo "╔══════════════════════════════════════╗"
echo "║   ⏰ Apple Reminders Setup           ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "Create these lists in Apple Reminders:"
echo ""
echo "  1. ⚡ Do Now"
echo "     → Micro-tasks ≤15 min"
echo "     → Aggressive nag: creation → +30m → +1hr → hourly"
echo ""
echo "  2. 📍 Location"
echo "     → Location-triggered tasks"
echo "     → Fires on arrive/leave geofence"
echo ""
echo "  3. 🔄 Follow Up"
echo "     → Waiting on someone"
echo "     → Daily check-in cadence"
echo ""
echo "  4. 🏠 Shared"
echo "     → Shared with partner"
echo "     → Both get notified"
echo ""
echo "  5. 🛒 Groceries (optional)"
echo "     → Shopping list"
echo ""
echo "  6. 🏡 Home (optional)"
echo "     → Household tasks"
echo ""
echo "After creating lists:"
echo "  1. Share '🏠 Shared' list with your partner"
echo "  2. Set up location geofences on iPhone:"
echo "     Settings → Privacy → Location Services"
echo "     Pre-configure: home, office, gym, grocery store"
echo ""
