#!/bin/bash
# OpenClaw Notebook — Calendar Setup
# Guide for creating Google Calendar sub-calendars.

echo ""
echo "╔══════════════════════════════════════╗"
echo "║   📅 Calendar Setup                  ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "Create these sub-calendars in Google Calendar:"
echo ""
echo "  1. Work Blocks (Blue)"
echo "     → Time-blocked tasks ≥15 min"
echo ""
echo "  2. Personal (Green)"
echo "     → Shared with partner — dates, trips, calls"
echo ""
echo "  3. Habits & Routines (Yellow)"
echo "     → Gym, walks, fixed routines"
echo ""
echo "  4. Deadlines (Red)"
echo "     → Visa, anniversaries, birthdays"
echo "     → Set auto-reminders at -14, -7, -1 day"
echo ""
echo "Steps:"
echo "  1. Go to calendar.google.com"
echo "  2. Click '+' next to 'Other calendars'"
echo "  3. Select 'Create new calendar'"
echo "  4. Create each calendar above"
echo "  5. Share 'Personal' calendar with your partner"
echo ""
echo "Then install Notion Calendar (or Morgen) as your UI layer."
echo ""
echo "Google Calendar API setup for gog:"
echo "  1. Go to console.cloud.google.com"
echo "  2. Create a project, enable Calendar API"
echo "  3. Create OAuth credentials"
echo "  4. Run: gog auth"
echo ""
